id: P004574
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19197
  title: 'ཁམས་འབྲོང་སྟོད་ཡུལ་གྱི་འདམ་བླ་ཚང་དགོན་པའི་བླ་མ་ཀུན་བཟང་ཆོས་དབྱིངས་རྡོ་རྗེའི་རྣམ་ཐར་རིན་ཆེན་ཕྲེང་མཛེས། '
  author: ''
  volumes:
    6efdfe66f9fe4056aa77698efe7c7a6a:
      image_group_id: I2PD19207
      title: ''
      volume_number: 1
      total_pages: 226
