id: opecha:P004574
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19197
  title: 'ཁམས་འབྲོང་སྟོད་ཡུལ་གྱི་འདམ་བླ་ཚང་དགོན་པའི་བླ་མ་ཀུན་བཟང་ཆོས་དབྱིངས་རྡོ་རྗེའི་རྣམ་ཐར་རིན་ཆེན་ཕྲེང་མཛེས། '
  volume: ''
  author: ''
